gilded-rose.legendary-price=999
gilded-rose.expired-discount-rate=0.5
gilded-rose.base-prices.aged-brie=50
gilded-rose.base-prices.backstage-pass=80
gilded-rose.base-prices.conjured-mana-cake=25
gilded-rose.base-prices.sulfuras=999
gilded-rose.base-prices.normal-item=20
